=== hrahmadi71/REsolution/web/src/test/resources/dataset/interview-it.dtd
<!ELEMENT dataset (
   (CITY|
    COMMENTS|
    COMPANY|
    DATABASECHANGELOG|
    DATABASECHANGELOGLOCK|
    DBMAINTAIN_SCRIPTS|
    FEEDBACKS|
    INTERVIEW|
    INTERVIEW_QUESTION|
    POSITIONS|
    RESET_PASSWORD|
    TECHNOLOGIES|
    USERS)*)>

<!ELEMENT CITY EMPTY>
<!ATTLIST CITY
    ID CDATA #REQUIRED
    CITYNAME CDATA #IMPLIED
>

<!ELEMENT COMMENTS EMPTY>
<!ATTLIST COMMENTS
    ID CDATA #REQUIRED
    QUESTION_ID CDATA #REQUIRED
    RATE CDATA #REQUIRED
    AUTHORNAME CDATA #REQUIRED
    EMAIL CDATA #IMPLIED
    COMMENTTEXT CDATA #REQUIRED
    USERPICURL CDATA #IMPLIED
>

<!ELEMENT COMPANY EMPTY>
<!ATTLIST COMPANY
    ID CDATA #REQUIRED
    COMPANYNAME CDATA #IMPLIED
    COMPANYPHONE CDATA #IMPLIED
    COMPANYLOGOURL CDATA #IMPLIED
    COMPANYADDRESS CDATA #IMPLIED
    COMPANYWEBPAGE CDATA #IMPLIED
    COMPANYTYPE CDATA #IMPLIED
>

<!ELEMENT DATABASECHANGELOG EMPTY>
<!ATTLIST DATABASECHANGELOG
    ID CDATA #REQUIRED
    AUTHOR CDATA #REQUIRED
    FILENAME CDATA #REQUIRED
    DATEEXECUTED CDATA #REQUIRED
    ORDEREXECUTED CDATA #REQUIRED
    EXECTYPE CDATA #REQUIRED
    MD5SUM CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    COMMENTS CDATA #IMPLIED
    TAG CDATA #IMPLIED
    LIQUIBASE CDATA #IMPLIED
>

<!ELEMENT DATABASECHANGELOGLOCK EMPTY>
<!ATTLIST DATABASECHANGELOGLOCK
    ID CDATA #REQUIRED
    LOCKED CDATA #REQUIRED
    LOCKGRANTED CDATA #IMPLIED
    LOCKEDBY CDATA #IMPLIED
>

<!ELEMENT DBMAINTAIN_SCRIPTS EMPTY>
<!ATTLIST DBMAINTAIN_SCRIPTS
    CHECKSUM CDATA #IMPLIED
    EXECUTED_AT CDATA #IMPLIED
    FILE_LAST_MODIFIED_AT CDATA #IMPLIED
    FILE_NAME CDATA #IMPLIED
    SUCCEEDED CDATA #IMPLIED
>

<!ELEMENT FEEDBACKS EMPTY>
<!ATTLIST FEEDBACKS
    ID CDATA #REQUIRED
    CREATETIME CDATA #IMPLIED
    CHECKED CDATA #IMPLIED
    FEEDBACKTEXT CDATA #IMPLIED
    EMAIL CDATA #IMPLIED
>

<!ELEMENT INTERVIEW EMPTY>
<!ATTLIST INTERVIEW
    ID CDATA #REQUIRED
    USERID CDATA #REQUIRED
    FEEDBACK CDATA #IMPLIED
    CREATED CDATA #IMPLIED
    CITY_ID CDATA #IMPLIED
    POSITION_ID CDATA #IMPLIED
    TECHNOLOGY_ID CDATA #IMPLIED
    COMPANY_ID CDATA #IMPLIED
>

<!ELEMENT INTERVIEW_QUESTION EMPTY>
<!ATTLIST INTERVIEW_QUESTION
    ANSWER CDATA #IMPLIED
    CREATED CDATA #IMPLIED
    ID CDATA #REQUIRED
    INTERVIEWID CDATA #IMPLIED
    QUESTION CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    USERID CDATA #IMPLIED
>

<!ELEMENT POSITIONS EMPTY>
<!ATTLIST POSITIONS
    ID CDATA #REQUIRED
    POSITIONGROUP CDATA #IMPLIED
    POSITIONNAME CDATA #IMPLIED
>

<!ELEMENT RESET_PASSWORD EMPTY>
<!ATTLIST RESET_PASSWORD
    EMAIL CDATA #IMPLIED
    HASH CDATA #REQUIRED
>

<!ELEMENT TECHNOLOGIES EMPTY>
<!ATTLIST TECHNOLOGIES
    ID CDATA #REQUIRED
    TECHNOLOGYNAME CDATA #IMPLIED
>

<!ELEMENT USERS EMPTY>
<!ATTLIST USERS
    ID CDATA #REQUIRED
    NAME CDATA #IMPLIED
    PASSWORD CDATA #IMPLIED
    EMAIL CDATA #IMPLIED
>

=== hrahmadi71/REsolution/web/src/test/resources/dataset/InterviewResource/interview-list.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "src/test/resources/dataset/interview-it.dtd">
<dataset>
    <USERS ID="10" NAME="Name" PASSWORD="5f4dcc3b5aa765d61d8327deb882cf99" EMAIL="email@mail.com"/>
    <TECHNOLOGIES ID="1" TECHNOLOGYNAME="APL"/>
    <TECHNOLOGIES ID="2" TECHNOLOGYNAME="C"/>
    <TECHNOLOGIES ID="3" TECHNOLOGYNAME="C#/.NET"/>
    <POSITIONS ID="1" POSITIONGROUP="Development" POSITIONNAME="Junior Software Engineer"/>
    <POSITIONS ID="2" POSITIONGROUP="  Development" POSITIONNAME="Software Engineer"/>
    <POSITIONS ID="3" POSITIONGROUP="Development" POSITIONNAME="Senior Software Engineer"/>
    <COMPANY ID="1" COMPANYNAME="COMPANY1"/>
    <COMPANY ID="2" COMPANYNAME="COMPANY2"/>
    <COMPANY ID="3" COMPANYNAME="COMPANY3"/>
    <CITY ID="1" CITYNAME="CITY1"/>
    <CITY ID="2" CITYNAME="CITY2"/>
    <CITY ID="3" CITYNAME="CITY3"/>
    <INTERVIEW ID="1" USERID="10" COMPANY_ID="1" TECHNOLOGY_ID="1" POSITION_ID="1"  CITY_ID="1" FEEDBACK="FEEDBACK 1"  />
    <INTERVIEW ID="2" USERID="10" COMPANY_ID="2" TECHNOLOGY_ID="2" POSITION_ID="2"  CITY_ID="2" FEEDBACK="FEEDBACK 2"/>
    <INTERVIEW ID="3" USERID="10" COMPANY_ID="3" TECHNOLOGY_ID="3" POSITION_ID="3"  CITY_ID="3" FEEDBACK="FEEDBACK 3" />
</dataset>
